### ISSUE TITLE
 assert False, 'No exists .mat file!' when attack

### ISSUE THREAD

**Issue by cuge1995** [Gorilla-Lab-SCUT/GeoA3#2]

**Comment by Yuxin-Wen** [comment]
Thanks for rising this issue! Since different models perform slightly differently on the given data, directly adopt the same mat file might overstate the success rate of an attack (some instances might be incorrectly classified even without attack). Thus, the mat file is recommended to be generated yourself. We have renewed the README file and provide a command to do so. And we also upload one to google driver for quick validation [here](https://drive.google.com/file/d/1mFsEyvfetQDlA30pHijN3S1wAlhwuemk/view?usp=sharing) ：）
